Repository ztkmkoo/dss, pull requests merged in 2020-08, with the labels that each got.

#78 [#58] Add lombok.config file
  lombok.config
Labels: feature

#77 Add sonarquebe badge to README.md #72
  README.md
Labels: documentation, feature

#89 [#87] add dss server performance test guide
  benchmark/dss/GUIDE.md
Labels: documentation

#88 [DSS-68]Fix Maven dependencies
  dss-core/pom.xml
  dss-server/pom.xml
  pom.xml
Labels: feature

#85 [#84] fix major code smell
  dss-core/src/test/java/io/github/ztkmkoo/dss/core/exception/DssRestInvalidContentTypeMappingExceptionTest.java
  dss-core/src/test/java/io/github/ztkmkoo/dss/core/exception/DssRestServiceMappingExceptionTest.java
  dss-core/src/test/java/io/github/ztkmkoo/dss/core/message/rest/DssRestMasterActorCommandRequestTest.java
  dss-core/src/test/java/io/github/ztkmkoo/dss/core/network/rest/handler/DssRestChannelInitializerTest.java
Labels: bug, refactoring

#83 Feature/81 network interface
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/DssActorService.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/rest/service/DssRestActorService.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/network/DssActorAcceptable.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/network/DssChannel.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/network/DssChannelInitializer.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/network/DssChannelProperty.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/network/DssHandler.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/network/rest/DssRestChannel.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/network/rest/handler/DssRestChannelInitializer.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/network/rest/handler/DssRestHandler.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/network/rest/property/DssRestChannelProperty.java
  dss-server/src/main/java/io/github/ztkmkoo/dss/server/DssServer.java
  dss-server/src/main/java/io/github/ztkmkoo/dss/server/rest/DssRestServer.java
Labels: core, discussion, feature, help wanted

#95 Add tutorial link to README.md
  README.md
Labels: bug, documentation

#94 [#62] Add example sub module
  .gitignore
  dss-example/pom.xml
  pom.xml
Labels: feature

#91 [#44] Add rest server tests
  dss-server/pom.xml
  dss-server/src/test/java/io/github/ztkmkoo/dss/server/rest/DssRestServerTest.java
Labels: feature, test

#76 [#63] Migrate project to jdk 11
  .travis.yml
  pom.xml
Labels: feature

#93 [#90] NullPointerException in DssRestActorJsonService.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/exception/DssRestRequestMappingException.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/rest/DssRestServiceActor.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/rest/service/DssRestActorJsonService.java
Labels: bug, feature, service

#101 [#97] bug fix: can't get response when using charset error.
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/network/rest/entity/DssRestRequest.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/network/rest/enumeration/DssRestContentType.java
Labels: bug, feature

#106 [#87] feature/87 Load test dss rest server performance
  benchmark/dss/20200812/RecordedSimulation.scala
  benchmark/dss/20200812/Result.md
  benchmark/dss/20200812/pom.xml
  benchmark/dss/20200812/src/main/java/Application.java
  benchmark/dss/20200812/src/main/java/HelloService.java
  benchmark/dss/20200812/src/main/java/MyServiceResponse.java
  benchmark/dss/20200812/src/main/resources/META-INF/MANIFEST.MF
Labels: feature, test

#103 [#100] Add rest server basic sample code.
  dss-example/pom.xml
  dss-example/src/main/java/io/github/ztkmkoo/dss/example/http/tutorial/Application.java
  dss-example/src/main/java/io/github/ztkmkoo/dss/example/http/tutorial/MyService.java
  dss-example/src/main/java/io/github/ztkmkoo/dss/example/http/tutorial/MyServiceRequest.java
  dss-example/src/main/java/io/github/ztkmkoo/dss/example/http/tutorial/MyServiceResponse.java
  pom.xml
Labels: discussion, feature

#112 [#80] Set netty and akka log level from service level
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/network/rest/DssRestChannel.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/network/rest/enumeration/DssLogLevel.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/network/rest/property/DssRestChannelProperty.java
  dss-server/src/main/java/io/github/ztkmkoo/dss/server/rest/DssRestServer.java
  dss-server/src/test/java/io/github/ztkmkoo/dss/server/rest/DssRestServerTest.java
Labels: feature

#108 [#36] Inspect code style
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/exception/DssUserActorDuplicateBehaviorCreateException.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/rest/DssRestPathResolver.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/rest/DssRestServiceActor.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/rest/entity/DssRestContentInfo.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/rest/entity/DssRestServiceRequest.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/rest/entity/DssRestServiceRequestDefaultImpl.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/rest/service/DssRestActorFormDataService.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/actor/rest/service/DssRestActorJsonService.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/exception/DssRestInvalidContentTypeMappingException.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/message/rest/DssRestChannelHandlerCommandResponse.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/message/rest/DssRestChannelInitializerCommandHandlerUnregistered.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/message/rest/DssRestMasterActorCommandRequest.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/message/rest/DssRestServiceActorCommandRequest.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/network/rest/entity/DssRestRequest.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/network/rest/enumeration/DssLogLevel.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/network/rest/enumeration/DssRestContentType.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/network/rest/enumeration/DssRestMethodType.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/network/rest/exception/NotSupportedRestMethodException.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/network/rest/handler/DssRestChannelInitializer.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/network/rest/handler/DssRestHandler.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/network/rest/handler/DssRestSslChannelInitializer.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/network/rest/property/DssRestChannelProperty.java
  dss-core/src/main/java/io/github/ztkmkoo/dss/core/util/StringUtils.java
  dss-core/src/test/java/io/github/ztkmkoo/dss/core/actor/AbstractDssActorTest.java
  dss-core/src/test/java/io/github/ztkmkoo/dss/core/actor/rest/DssRestMasterActorTest.java
  dss-core/src/test/java/io/github/ztkmkoo/dss/core/actor/rest/service/DssRestActorJsonServiceTest.java
  dss-core/src/test/java/io/github/ztkmkoo/dss/core/network/rest/handler/DssRestHandlerTest.java
  dss-example/src/main/java/io/github/ztkmkoo/dss/example/http/tutorial/MyService.java
  dss-example/src/main/java/io/github/ztkmkoo/dss/example/http/tutorial/MyServiceRequest.java
  dss-example/src/main/java/io/github/ztkmkoo/dss/example/http/tutorial/MyServiceResponse.java
  dss-server/pom.backup.xml
  dss-server/src/main/java/io/github/ztkmkoo/dss/server/rest/DssRestServer.java
  dss-server/src/test/java/io/github/ztkmkoo/dss/server/rest/DssRestServerTest.java
Labels: feature, refactoring
